### ISSUE TITLE
20 March 2024

### ISSUE THREAD

**Issue by kushagra-singhh** [Trident09/Semester-6#1]
Write a Lex program to recongnise floating point numbers.
Write a lex program to count number of words in a text file.
Write a lex program to identify keywords and convert it into upper-case. // not done
Write a lex program to count number of vowels and consonants.
Write a lex to count the number of identifiers, keywords and digits.

**Comment by Trident09** [comment]
On it

**Comment by Trident09** [comment]
added all functional code
