### ISSUE TITLE
24 April 2024

### ISSUE THREAD

**Issue by kushagra-singhh** [Trident09/Semester-6#2]
## Q1 Using JFLAP, implement :
- desing a dfa , nfa , for any general language.
- design dfa for a given regex.

## Q2 write a cpp program to find the first and follow for all the non terminal present in the gramar.

**Comment by kushagra-singhh** [comment]
https://www.jflap.org/jflaptmp/

**Comment by kushagra-singhh** [comment]
# ε = {a,b}
## Design DFA for the following : 

- L1 = aⁿbᵐ | n,m ≥ 0
-  L2 = { w : | w | mod3 = 0 }
- L3 = aⁿb | n ≥ 0
-  L4 = ab* (a+b)*    -     All strings with prefix ab 
# ε = {0,1}
- Construct a DFA over the string which does not contain substring 001.

# ε = {a,b}
## Construct a NFA that accepts set of strings with : 
- Exactly one 'a'
- Atleast one 'a'
- No more than 3 'a'
- Atleast 1 'a' and 2 'b'
- Exactly 2 'a' and more than 2 'b'

**Comment by kushagra-singhh** [comment]
all questions are added for the dfa part

**Comment by Trident09** [comment]
cpp not done
